### ISSUE TITLE
Add to ZIP

### ISSUE THREAD

**Issue by frederikprijck** [frederikprijck/limesurvey-plugin-raygun-pulse#1]
@Shnoulle can you add this plugin to the ZIP aswell (if you agree with the plugin implementation)? :-)

**Comment by Shnoulle** [comment]
Hi @frederikprijck : no because raygun is not a free (like a speech) tool.

For zipping on my server (on a git clone):

```
cd ~/git/RaygunPulse.git
git archive --prefix=RaygunPulse/  -o /home/webuser/htdocs/extensions/IMG/auto/RaygunPulse.zip master
```

**Comment by frederikprijck** [comment]
What do you mean with **no** ? Raygun isn't free, but the RaygunJS code is MIT licensed so we are allowed to reuse it in MIT projects.

**Comment by Shnoulle** [comment]
Yes, but, for example, because of ethical : i don't promote Google ( neither google map or google analytics), but only free alternative.

Then i don't take the file on my script on my server :).

**Comment by frederikprijck** [comment]
Ah okay mate. I completely understand. No problem !
